### ISSUE TITLE
Delivery Man

### ISSUE THREAD

**Issue by Keystirras** [Keystirras/TFoC#17]
https://www.spigotmc.org/resources/delivery-man-easy-to-setup-fully-configurable-mysql-custom-rewards.20185/

**Comment by JessTheKiwi** [comment]
(Daily rewards, weekly rewards, Monthly rewards)

**Comment by JessTheKiwi** [comment]
oops

**Comment by JessTheKiwi** [comment]
Daily - 50 Rank XP
            $100,000
            100 XP
Weekly - 250 Rank XP
            $500,000
              450XP
Monthly - 1000 Rank XP
             $1,000,000
               1000XP

**Comment by Keystirras** [comment]
Purchased plugin.

**Comment by Keystirras** [comment]
Took  roughly 20% of the exp off

Finished. Need to spawn NPC somewhere in the new spawn when i get that setup.

**Comment by Keystirras** [comment]
Spawned.
