### ISSUE TITLE
Vote Crates and Rewards

### ISSUE THREAD

**Issue by JessTheKiwi** [Keystirras/TFoC#20]
- Spawner Pickaxe
- Spawn eggs
- Spawner
- Money
- Mcmmo vouchers
- XP
- God Apples
- Diamonds
- Gold
- Rare blocks (Sponges)

**Comment by JessTheKiwi** [comment]
+ Nametags
+ Sword 1,2,3,4
+ Pick 1,2,3,
+ Axe 1,2,3
+ Spade 1, 2, 3

**Comment by JessTheKiwi** [comment]
Spawner Pickaxe                1%
Zombie Spawn egg
Skeleton Spawn egg
Bat Spawn Egg
Blaze Spawn Egg
Cow spawn egg
Sheep spawn egg
Chicken Spawn egg
Pig Spawn egg
0.01% Chance Zombie Spawner
$1000
$5000
$50000  0.5%
$10000  1%
5 Mcmmo Credits
10 Mcmmo credits
25 Mcmmo credits 0.4%
10 XP points
15 XP points
20 XP points
32 God Apples
1-16 diamonds
32 Gold
Sponge
16 Nametags
Sword 1 (Windcleaver) 
Sword 2 (Arondite)
Sword 3 (Goldryn)
Sword 4 (Soulsiphon)
Pick 1 (Netherbane)
Pick 2 (Endovier )
Pick 3 (Exorcism)
Axe 1 (Ironbark)
Axe 2 (Fleshrender)
Axe 3 (Orynth)
Spade 1 (Spada)
Spade 2 (Jinx)
Spade 3 (Morath)

**Comment by JessTheKiwi** [comment]
Spawner Pickaxe                0.1%
Zombie Spawn egg            1%
Skeleton Spawn egg           1%
Bat Spawn Egg                    0.5%
Blaze Spawn Egg                 0.34%
Cow spawn egg                    2%
Sheep spawn egg                  3%
Chicken Spawn egg               2%
Pig Spawn egg                       3%
 Zombie Spawner                0.01%
$1000                                  4%
$5000                                  3%
$50000                            0.25%
$10000                                 2%
5 Mcmmo Credits              3%
10 Mcmmo credits             2%
25 Mcmmo credits             0.8%
10 XP points                        3%
15 XP points                        2%
20 XP points                        1%
32 God Apples                     5%
1-16 diamonds                     4%
32 Gold                                6%
8 Sponge                              4%
16 Nametags                        4%
Sword 1 (Windcleaver)         1%
Sword 2 (Arondite)                2%
Sword 3 (Goldryn)                 3%
Sword 4 (Soulsiphon)           4%
Pick 1 (Netherbane)             2%
Pick 2 (Endovier )                  3%
Pick 3 (Exorcism)                  4%
Axe 1 (Ironbark)                   2%
Axe 2 (Fleshrender)              3%
Axe 3 (Orynth)                     4%
Spade 1 (Spada)                 4%
Spade 2 (Jinx)                      5%
Spade 3 (Morath)                6%

**Comment by Keystirras** [comment]
Configuration is done. Just need to place in spawn.

**Comment by Keystirras** [comment]
Spawned
