### ISSUE TITLE
New earnable ranks

### ISSUE THREAD

**Issue by Keystirras** [Keystirras/TFoC#4]

**Comment by JessTheKiwi** [comment]
Terraseer

**Comment by JessTheKiwi** [comment]
Draugr - The draugr or draug (Old Norse: draugr, plural draugar; modern Icelandic: draugur, Faroese: dreygur and Danish, Swedish and Norwegian: draugen), also called aptrganga or aptrgangr, literally "again-walker" (Icelandic: afturganga) is an undead creature from Norse mythology, a subset of Germanic mythology.
![draugr](https://cloud.githubusercontent.com/assets/25399657/22395781/cedf2ee4-e5ac-11e6-9991-a475b3701465.jpg)

**Comment by JessTheKiwi** [comment]
Satyr - one of a class of lustful, drunken woodland gods. In Greek art they were represented as a man with a horse's ears and tail, but in Roman representations as a man with a goat's ears, tail, legs, and horns.
![satyr](https://cloud.githubusercontent.com/assets/25399657/22395790/1924aa2e-e5ad-11e6-9a31-04fef6a6d455.jpg)

**Comment by JessTheKiwi** [comment]
# Fantasy Themed:
## 
 **Imp** - a small, mischievous devil or sprite.
**Satyr** - one of a class of lustful, drunken woodland gods. In Greek art they were represented as a man with a horse's ears and tail, but in Roman representations as a man with a goat's ears, tail, legs, and horns.
**Centaur** - Centaurs are half-human, half-horse creatures in Greek mythology. They have the body of a horse and the torso, head and arms of a man. They were considered to be the children of Ixion, king of the Lapiths, and Nephele, a cloud made in the image of Hera
**Basilisk** - "King of Serpents"
**Wyvern** - a winged two-legged dragon with a barbed tail. <3<3<3
**Myr** - shortened of myrmidon  - a follower or subordinate of a powerful person, typically one who is unscrupulous or carries out orders unquestioningly.
**Chimera** - (in Greek mythology) a fire-breathing female monster with a lion's head, a goat's body, and a serpent's tail.
**Valkyr** - each of Odin's twelve handmaids who conducted the slain warriors of their choice from the battlefield to Valhalla.
**Newt** - A newt is a salamander
**Chupacabra** The chupacabra or chupacabras (Spanish pronunciation: [tʃupaˈkaβɾas], literally "goat-sucker"; from "chupar", "to suck", and "cabra", "goat") is a legendary creature in the folklore of parts of the Americas, with its first purported sightings reported in Puerto Rico.
Inugami - Inugami (犬神, lit. "dog god"), like kitsunetsuki, is a spiritual possession by the spirit of a dog, widely known about in western Japan.

**Comment by Keystirras** [comment]
Done.
