### ISSUE TITLE
Re-do permissons

### ISSUE THREAD

**Issue by Keystirras** [Keystirras/TFoC#8]

**Comment by Keystirras** [comment]
Perks for each rankup:

Member:
    Nick (Costs 100k)
    Comes with Color ^
    Create Town
    Auction
Next oneidk:
    Nick magic
    /back
    /workbench
Next:
    /repair (free)
    /enderchest
    /workbench
next:
        /sethome 5
    /playervault 5
    /jobs (4)
next:
    /seen
    /time
    /weather
    one 1 hour voucher for BattleLevels
next:
    /nick (free)
    /fly
    /day
    /night

**Comment by JessTheKiwi** [comment]
maybe more spread?

**Comment by Keystirras** [comment]
Done and uploaded.

**Comment by Keystirras** [comment]
Im a little dumb ass yes i am.... I saved the rules in the permisons file....

**Comment by Keystirras** [comment]
Fixed. Saved, made a backup this time...
